# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vehiclemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='model_type',
            field=models.CharField(choices=[('car', 'Carro'), ('motorcycle', 'Moto')], default='motorcycle', max_length=20),
        ),
    ]
