# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160722_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Vermelho'), ('blue', 'Azul'), ('green', 'Verde'), ('white', 'Branco'), ('grey', 'Cinza'), ('black', 'Preto')], max_length=20)),
                ('mileage', models.IntegerField()),
                ('engine', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.VehicleModel')),
            ],
        ),
    ]
